version: '2.2'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: currency_exchange_service
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"