version: '2.2'

services:
  mysql:
    build:
      context: ./
      dockerfile: manifests/deploy/local/setdb/Dockerfile
    security_opt:
      - seccomp:unconfined
    ports:
      - 3366:3306
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.2
    container_name: hktv_ty_mwms_backend_mysql
    environment:
      - TZ=Asia/Hong_Kong
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: admin1234
      TZ: Asia/Taipei
    restart: always
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.3
    volumes:
      - ./manifests/deploy/local/rabbitmq/rabbitmq-enabled-plugins:/etc/rabbitmq/enabled_plugins
      - ./manifests/deploy/local/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.conf
      - ./manifests/deploy/local/rabbitmq/rabbitmq-defs.json:/etc/rabbitmq/definitions.json
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: hktv_ty_mwms_backend
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.4
    depends_on:
      - mysql
      - rabbitmq
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
      - cluster-creator
    ports:
      - "8091:8091"
      - "5005:5005"
    extra_hosts:
      - "host.docker.internal:host-gateway"
#  app_ii:
#    build:
#      context: ./
#      dockerfile: Dockerfile
#    container_name: hktv_ty_mwms_backend_ii
#    networks:
#      hktv_ty_mwms_backend:
#        ipv4_address: 172.19.0.12
#    depends_on:
#      - mysql
#      - rabbitmq
#      - redis-node1
#      - redis-node2
#      - redis-node3
#      - redis-node4
#      - redis-node5
#      - redis-node6
#      - cluster-creator
#      - app
#    ports:
#      - "8092:8091"
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
  cluster-creator:
    image: redis:7.2.0-alpine3.18
    container_name: redis-cluster-creator
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.5
    entrypoint: redis-cli -a 1234 --cluster create redis-node1:6380 redis-node2:6381 redis-node3:6382 redis-node4:6383 redis-node5:6384 redis-node6:6385 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node1
      - redis-node2
      - redis-node3
      - redis-node4
      - redis-node5
      - redis-node6
  redis-node1:
    image: redis:7.2.0
    container_name: redis-node1
    ports:
      - "6380:6380"
      - "16380:16380"
    volumes:
      - ./manifests/deploy/local/redis/redis-6380.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.6
  redis-node2:
    image: redis:7.2.0
    container_name: redis-node2
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ./manifests/deploy/local/redis/redis-6381.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.7
  redis-node3:
    image: redis:7.2.0
    container_name: redis-node3
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ./manifests/deploy/local/redis/redis-6382.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.8
  redis-node4:
    image: redis:7.2.0
    container_name: redis-node4
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ./manifests/deploy/local/redis/redis-6383.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.9
  redis-node5:
    image: redis:7.2.0
    container_name: redis-node5
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ./manifests/deploy/local/redis/redis-6384.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.10
  redis-node6:
    image: redis:7.2.0
    container_name: redis-node6
    ports:
      - "6385:6385"
      - "16385:16385"
    volumes:
      - ./manifests/deploy/local/redis/redis-6385.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    networks:
      hktv_ty_mwms_backend:
        ipv4_address: 172.19.0.11

networks:
  hktv_ty_mwms_backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24